//
//  geo.h
//  engine::core — geometry processing
//
//  Offline/bake-time mesh operations that turn rough procedural geometry into a single, clean,
//  performant asset. Two stages, composable:
//    1. meshCapsules(): union a set of round-cones (tapered capsules) into ONE watertight manifold
//       via a signed-distance field + Naive Surface Nets. Closes gaps, merges overlapping tubes,
//       rounds joints (optional smooth-union) — the fix for "a pile of tubes" (trees, rock blobs).
//    2. simplify(): quadric-error edge-collapse decimation to a triangle budget.
//
//  Pure data: operates on engine::MeshData (position + normal, glm), no graphics/RHI dependency.
//  Normals are (re)generated by these passes; UVs/tangents are NOT preserved (topology changes),
//  so downstream code should treat outputs as freshly-attributed meshes.
//

#pragma once

#include <cstddef>
#include <span>
#include <vector>

#include <glm/glm.hpp>

#include "engine/core/geometry/mesh.h"

namespace engine::geo {

// A round cone (tapered capsule): the swept sphere whose radius varies linearly from `ra` at `a` to
// `rb` at `b`. `ra == rb` is a capsule; `a == b` is a sphere. Trees/rocks are unions of these.
struct Capsule {
    glm::vec3 a{0.0f};
    glm::vec3 b{0.0f};
    float     ra{1.0f};
    float     rb{1.0f};
};

struct MesherParams {
    float voxel   = 0.1f;    // grid cell size in world units (smaller = finer surface, slower)
    float smooth  = 0.0f;    // smooth-union radius (0 = hard min); rounds where capsules meet
    float padding = -1.0f;   // extra AABB margin around the capsules; < 0 ⇒ auto (2 cells + max radius)
};

// Union the capsules into one watertight mesh (Naive Surface Nets over the capsule-union SDF).
// Vertex normals come from the SDF gradient (smooth). Returns an empty mesh if `capsules` is empty
// or the grid would be degenerate.
MeshData meshCapsules(std::span<const Capsule> capsules, const MesherParams& params = {});

// Quadric-error (Garland–Heckbert) edge-collapse simplification down to ~`targetTriangles`
// (stops early if no further collapse is valid). Recomputes vertex normals. Robust to the closed
// manifolds produced by meshCapsules; guards against normal-flipping (foldover) collapses.
MeshData simplify(const MeshData& mesh, std::size_t targetTriangles);

} // namespace engine::geo
